# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
- postgresql

before_install:
- psql -c 'create database job4j_database-test;' -U postrgress
- psql -c 'CREATE SCHEMA tracker;' -U postrgress

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуmailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -mailto:msg2fedorov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always