-- inserting some date
INSERT INTO tracker.company (name) VALUES ('Sberbank');
INSERT INTO tracker.company (name) VALUES ('Tinkoff');
INSERT INTO tracker.company (name) VALUES ('Innova');
INSERT INTO tracker.company (name) VALUES ('Telegram');
INSERT INTO tracker.company (name) VALUES ('Russian Post');
INSERT INTO tracker.company (name) VALUES ('Aeroflot');
INSERT INTO tracker.company (name) VALUES ('Telegram');
INSERT INTO tracker.person (name, company_id) VALUES ('person_1', 3);
INSERT INTO tracker.person (name, company_id) VALUES ('person_2', 2);
INSERT INTO tracker.person (name, company_id) VALUES ('person_3', 4);
INSERT INTO tracker.person (name, company_id) VALUES ('person_5', 1);
INSERT INTO tracker.person (name, company_id) VALUES ('person_6', 1);
INSERT INTO tracker.person (name, company_id) VALUES ('person_8', 1);
INSERT INTO tracker.person (name, company_id) VALUES ('person_12', 3);
INSERT INTO tracker.person (name, company_id) VALUES ('person_21', 3);
INSERT INTO tracker.person (name, company_id) VALUES ('person_22', 3);
INSERT INTO tracker.person (name, company_id) VALUES ('person_41', 2);
INSERT INTO tracker.person (name, company_id) VALUES ('person_51', 2);
INSERT INTO tracker.person (name, company_id) VALUES ('person_16', 4);
INSERT INTO tracker.person (name, company_id) VALUES ('person_56', 4);
INSERT INTO tracker.person (name, company_id) VALUES ('person_14', 5);
INSERT INTO tracker.person (name, company_id) VALUES ('person_13', 5);
INSERT INTO tracker.person (name, company_id) VALUES ('person_31', 6);
INSERT INTO tracker.person (name, company_id) VALUES ('person_71', 6);
INSERT INTO tracker.person (name, company_id) VALUES ('person_81', 6);
INSERT INTO tracker.person (name, company_id) VALUES ('person_11', 6);