-- в строку сделал, потомцу что у меня читает построчно отсюда
CREATE TABLE tracker.item (id SERIAL PRIMARY KEY NOT NULL, name VARCHAR(100), description VARCHAR(150), creation_date DATE NOT NULL);
INSERT INTO tracker.item VALUES (1, 'Incoming mail', 'description_text_fifth', NOW());
INSERT INTO tracker.item VALUES (2, 'Incoming mail', 'description_text_fourth', NOW());
INSERT INTO tracker.item VALUES (3, 'Incoming mail', 'description_text_second', NOW());
INSERT INTO tracker.item VALUES (4, 'Incoming mail', 'description_text_third', NOW());
INSERT INTO tracker.item VALUES (5, 'Incoming mail', 'description_text_first', NOW());
INSERT INTO tracker.item VALUES (6, 'Incoming mail', 'description_text_fourth', NOW());
CREATE TABLE tracker.comment (id SERIAL PRIMARY KEY NOT NULL, comment VARCHAR(250), item_id INTEGER REFERENCES tracker.item(id));
INSERT INTO tracker.comment (id, comment, item_id) VALUES (1, 'commit_text_first', 3);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (2, 'commit_text_second', 2);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (3, 'commit_text_third', 4);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (4, 'commit_text_fourth', 1);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (5, 'commit_text_five', 1);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (6, 'commit_text_six', 1);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (7, 'commit_text_seven', 3);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (8, 'commit_text_eight', 3);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (9, 'commit_text_9', 3);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (10, 'commit_text_10', 2);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (11, 'commit_text_11', 2);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (12, 'commit_text_12', 4);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (13, 'commit_text_13', 4);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (14, 'commit_text_14', 5);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (15, 'commit_text_15', 5);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (16, 'commit_text_16', 6);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (17, 'commit_text_17', 6);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (18, 'commit_text_18', 6);
INSERT INTO tracker.comment (id, comment, item_id) VALUES (19, 'commit_text_19', 6);