INSERT INTO tracker.item (name, description, creation_date) VALUES ('Incoming mail', 'description_text_fifth', 'Wed 17 Dec 03:27:13 2018 PST');
INSERT INTO tracker.item (name, description, creation_date) VALUES ('Outcoming mail', 'description_text_fourth', NOW());
INSERT INTO tracker.item (name, description, creation_date) VALUES ('Inner mail', 'description_text_second', 'Wed 12 Dec 07:37:14 1990 PST');
INSERT INTO tracker.item (name, description, creation_date) VALUES ('Incoming mail', 'description_text_third', NOW());
INSERT INTO tracker.item (name, description, creation_date) VALUES ('Unsorted mail', 'description_text_first', 'Wed 11 Jan 11:32:17 1991 PST');
INSERT INTO tracker.item (name, description, creation_date) VALUES ('Inner mail', 'description_text_fourth', NOW());
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_first', 3);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_second', 2);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_third', 4);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_fourth', 1);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_five', 1);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_six', 1);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_seven', 3);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_eight', 3);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_9', 3);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_10', 2);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_11', 2);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_12', 4);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_13', 4);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_14', 5);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_15', 5);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_16', 6);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_17', 6);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_18', 6);
INSERT INTO tracker.comment (comment, item_id) VALUES ('commit_text_19', 6);